    function buildPage(){
        var head = document.createElement('header');
        var title = document.createElement("h1");
        var navLink1 = document.createElement("a")
        var navLink2 = document.createElement("a")
        navLink1.setAttribute("href", "#");
        navLink1.textContent = "Home";
        navLink1.setAttribute("style", "font-weight: 700;")
        navLink2.setAttribute("href", "#");
        navLink2.textContent = "Categories";
        navLink1.setAttribute("style", "color: white; margin-top: 30px; margin-left: 56px; text-decoration:none; font-size:20px; font-family: arial");
        navLink2.setAttribute("style", "color: white; margin-top: 30px; margin-left: 56px; text-decoration:none; font-size:20px; font-family: arial");
        head.setAttribute("style", "background-color:#52A7FA; color:white; display: flex; flex-direction: row; font-family: arial;");
        title.setAttribute("style", " margin-left: 30px;");
        title.textContent = "HighOnCoding";
        head.appendChild(title);
        head.appendChild(navLink1);
        head.appendChild(navLink2);
        var div1 = document.createElement("div");
        var curse = document.createElement("h2");
        var para1 = document.createElement("p");
        div1.setAttribute("style", 'background-color: #DDDEE1; margin-top: 30px; width: 95%; margin-left: 2.5%; padding-top:5px; padding-bottom: 1px;');
        curse.setAttribute("style", "color: #565A61; margin-left: 30px; font-size: 30px; font-family: arial; font-weight: 600;");
        curse.textContent = "Curse of the Current Reviews";
        para1.setAttribute("style", "margin-top: 40px; margin-left: 30px; margin-bottom: 10px; font-size: 16px; font-family: arial");
        para1.textContent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
        var div2 = document.createElement("div");
        var hello = document.createElement("h3");
        var para2 = document.createElement("p");
        var greendiv = document.createElement('div');
        var comments = document.createElement("h6");
        var likes = document.createElement("h6");
        hello.textContent = "Hello Watchkit";
        para2.textContent = "Tempus urna et pharetra pharetra massa. Arcu vitae elementum curabitur vitae nunc sed. Purus gravida quis blandit turpis cursus in hac habitasse platea. Tortor consequat id porta nibh venenatis cras sed felis. Justo donec enim diam vulputate. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Imperdiet dui accumsan sit amet nulla. Sociis natoque penatibus et magnis dis parturient. Lectus vestibulum mattis ullamcorper velit sed. Quam id leo in vitae. ";
        comments.textContent = "12 comments";
        likes.textContent = "124 likes";
        div2.setAttribute("style", "margin-top: 15px; width: 95%; margin-left: 2.5%;");
        hello.setAttribute("style", "font-weight: 100; font-family: arial; font-size: 26px; color:#52A7FA");
        para2.setAttribute("style", " font-size: 16px; font-family: arial; margin-top: 8px;");
        greendiv.setAttribute("style", "background-color: #EF9033; width: 95%; margin-left: 2.5%; display: flex; flex-direction: row; height: 30px;");
        comments.setAttribute("style", "color: white; font-weight: 500; margin-left: 8px; margin-right:25px; font-family: arial; font-size: 18px; margin-top: 4px;");
        likes.setAttribute("style", "color: white; font-weight: 500; font-family: arial; font-size: 18px;  margin-top: 4px;");
        div2.appendChild(hello);
        div2.appendChild(para2);
        greendiv.appendChild(comments);
        greendiv.appendChild(likes);
        var div3 = document.createElement("div");
        var intro = document.createElement("h3");
        var para3 = document.createElement("p");
        var greendiv2 = document.createElement('div');
        var comments2 = document.createElement("h6");
        var likes2 = document.createElement("h6");
        intro.textContent = "Introduction to Swift";
        para3.textContent = "Tempus urna et pharetra pharetra massa. Arcu vitae elementum curabitur vitae nunc sed. Purus gravida quis blandit turpis cursus in hac habitasse platea. Tortor consequat id porta nibh venenatis cras sed felis. Justo donec enim diam vulputate. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Imperdiet dui accumsan sit amet nulla. Sociis natoque penatibus et magnis dis parturient. Lectus vestibulum mattis ullamcorper velit sed. Quam id leo in vitae. ";
        comments2.textContent = "15 comments";
        likes2.textContent = "45 likes";
        div3.setAttribute("style", "margin-top: 15px; width: 95%; margin-left: 2.5%;");
        intro.setAttribute("style", "font-weight: 100; font-family: arial; font-size: 26px; color:#52A7FA");
        para3.setAttribute("style", " font-size: 16px; font-family: arial; margin-top: 8px;");
        greendiv2.setAttribute("style", "background-color: #EF9033; width: 95%; margin-left: 2.5%; display: flex; flex-direction: row; height: 30px;");
        comments2.setAttribute("style", "color: white; font-weight: 500; margin-left: 8px; margin-right:25px; font-family: arial; font-size: 18px; margin-top: 4px;");
        likes2.setAttribute("style", "color: white; font-weight: 500; font-family: arial; font-size: 18px;  margin-top: 4px;");
        div3.appendChild(intro);
        div3.appendChild(para3);
        greendiv2.appendChild(comments2);
        greendiv2.appendChild(likes2);
        div1.appendChild(curse);
        div1.appendChild(para1);
        document.body.appendChild(head);
        document.body.appendChild(div1);
        document.body.appendChild(div2);
        document.body.appendChild(greendiv);
        document.body.appendChild(div3);
        document.body.appendChild(greendiv2);
    }